### ISSUE TITLE
Dictionary key conflict in code?

### ISSUE THREAD

**Issue by obxBill** [cmdrmcdonald/EliteDangerousDataProvider#121]
2017-02-04T02:01:29 VoiceAttackPlugin:VA_Init1 [I] Initialising EDDI VoiceAttack plugin 
2017-02-04T02:01:29 EDDI:.ctor [I] EDDI 2.1.1-b3 starting 
2017-02-04T02:01:32 EDDI:.ctor [E] Failed to initialise System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey](IEnumerable`1 source, Func`2 keySelector)
   at EddiCompanionAppService.CompanionAppService.AugmentShipInfo(Ship ship, List`1 storedShips)
   at EddiCompanionAppService.CompanionAppService.ProfileFromJson(JObject json)
   at EddiCompanionAppService.CompanionAppService.ProfileFromJson(String data)
   at EddiCompanionAppService.CompanionAppService.Profile(Boolean forceRefresh)
   at EddiCompanionAppService.CompanionAppService..ctor()
   at EddiCompanionAppService.CompanionAppService.get_Instance()
   at Eddi.EDDI..ctor()

**Comment by obxBill** [comment]
Determined issue was caused by an extra duplicate entry in the ships.json file.  once that was cleared out, all worked well!
