### ISSUE TITLE
EDDI 2.2.2 Crash on Startup with Elite 2.3 Patch

### ISSUE THREAD

**Issue by awp3rator** [cmdrmcdonald/EliteDangerousDataProvider#180]
I upgraded today to EDDI 2.2.2 and it crashed on startup with Elite Dangerous 2.3 patch.  The program initially runs, then crashes.  From windows event viewer, I'm seeing the following.  I attempted to uninstall and reinstall EDDI completely, which worked until I entered my commander details in to the companion app dialogue.  Upon entering the account auth token from Frontier, EDDI displays an error message similar to the Event ID 1000 below.  After closing it refuses to re-open.

Event ID 1000
Faulting application name: EDDI.exe, version: 1.0.0.0, time stamp: 0x58ea4100
Faulting module name: KERNELBASE.dll, version: 10.0.14393.953, time stamp: 0x58ba586d
Exception code: 0xe0434352
Fault offset: 0x000da882
Faulting process id: 0x455c
Faulting application start time: 0x01d2b3103ab11650
Faulting application path: C:\Program Files (x86)\VoiceAttack\Apps\EDDI\EDDI.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: c4bfb3fc-baa8-453d-87fa-a303356170c5
Faulting package full name: 
Faulting package-relative application ID: 

Event ID 1026
Application: EDDI.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException
   at DynamicClass.CallSite.Target(System.Runtime.CompilerServices.Closure, System.Runtime.CompilerServices.CallSite, System.Object, System.String)
   at EddiCompanionAppService.CompanionAppService.ShipFromProfile(System.Object)
   at EddiCompanionAppService.CompanionAppService.ProfileFromJson(Newtonsoft.Json.Linq.JObject)
   at EddiCompanionAppService.CompanionAppService.ProfileFromJson(System.String)
   at EddiCompanionAppService.CompanionAppService.Profile(Boolean)
   at EddiCompanionAppService.CompanionAppService..ctor()
   at EddiCompanionAppService.CompanionAppService.get_Instance()
   at Eddi.MainWindow.setStatusInfo()
   at Eddi.MainWindow..ctor(Boolean)
   at Eddi.MainWindow..ctor()

Exception Info: System.Windows.Markup.XamlParseException
   at System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader, Boolean, System.Object, System.Xaml.Permissions.XamlAccessLevel, System.Uri)
   at System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream, System.Windows.Markup.ParserContext, System.Object, Boolean)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(System.IO.Stream, System.Windows.Markup.ParserContext)
   at System.Windows.Application.LoadComponent(System.Uri, Boolean)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at System.Windows.Application.Run()
   at Eddi.App.Main()

From the eddi.log file:
2017-04-11T22:09:03 EDDI:.ctor [I] EDDI 2.2.2 starting 
2017-04-11T22:09:03 EDDI:.ctor [I] On live 
2017-04-11T22:09:04 EDDI:.ctor [E] Failed to initialise Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot perform runtime binding on a null reference
   at CallSite.Target(Closure , CallSite , Object , String )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at EddiCompanionAppService.CompanionAppService.ShipFromProfile(Object json)
   at EddiCompanionAppService.CompanionAppService.ProfileFromJson(JObject json)
   at EddiCompanionAppService.CompanionAppService.ProfileFromJson(String data)
   at EddiCompanionAppService.CompanionAppService.Profile(Boolean forceRefresh)
   at EddiCompanionAppService.CompanionAppService..ctor()
   at EddiCompanionAppService.CompanionAppService.get_Instance()
   at Eddi.EDDI..ctor()

**Comment by awp3rator** [comment]
Please consider this closed, as it is a dup of report "EDDI companion API failure #179"
