### ISSUE TITLE
Unexpected problem

### ISSUE THREAD

**Issue by Minudra** [cmdrmcdonald/EliteDangerousDataProvider#35]
![image](https://cloud.githubusercontent.com/assets/23064904/19707049/3c2bcbf0-9b0d-11e6-8271-bb7ad7e8a280.png)

Version 2, trying to login to the Companion App. Did the code and this came up as the error. I have then closed EDDI and now cannot get the tabs to reopen to see if I can get the files to validate. I have the latest Beta version of VoiceAttack too.

Win 10 with Admin rights

**Comment by Minudra** [comment]
2016-10-25T22:33:36 EDDI:.ctor [I] EDDI 2.0.3 starting
2016-10-25T22:33:36 EDDI:.ctor [I] EDDI access to the companion app is disabled
2016-10-25T22:33:36 EDDI:.ctor [I] EDDI access to EDSM is disabled
2016-10-25T22:33:36 EDDNResponder:.ctor [I] Initialised EDDN responder 1.0.0
2016-10-25T22:33:36 EDSMResponder:.ctor [I] Initialised EDSM responder 1.0.0
2016-10-25T22:33:36 SpeechResponder:.ctor [I] Initialised Speech responder 1.0.0
2016-10-25T22:33:36 VoiceAttackResponder:.ctor [I] Started VoiceAttack responder
2016-10-25T22:33:36 EDDI:.ctor [I] EDDI 2.0.3 initialised
2016-10-25T22:33:36 EDDI:Start [I] Starting Galnet monitor
2016-10-25T22:33:36 EDDI:Start [I] Starting Journal monitor
2016-10-25T22:33:36 EDDI:Start [I] Starting Netlog monitor
2016-10-25T22:33:36 EDDI:Start [I] Started EDDN responder
2016-10-25T22:33:36 NetLogMonitor:Start [I] Cannot start netlog monitor - path missing
2016-10-25T22:33:36 EDDI:Start [W] Failed to start EDSM responder
2016-10-25T22:33:36 EDDI:Start [I] Started Speech responder
2016-10-25T22:33:36 EDDI:Start [I] Started VoiceAttack responder
2016-10-25T22:33:37 SpeechResponder:Reload [I] Reloaded Speech responder 1.0.0
2016-10-25T22:35:05 SpeechResponder:Reload [I] Reloaded Speech responder 1.0.0
2016-10-25T22:35:05 SpeechResponder:Reload [I] Reloaded Speech responder 1.0.0
2016-10-25T22:35:05 SpeechResponder:Reload [I] Reloaded Speech responder 1.0.0
2016-10-25T22:35:05 SpeechResponder:Reload [I] Reloaded Speech responder 1.0.0
2016-10-25T22:35:05 SpeechResponder:Reload [I] Reloaded Speech responder 1.0.0
2016-10-25T22:35:05 SpeechResponder:Reload [I] Reloaded Speech responder 1.0.0
2016-10-25T22:35:05 SpeechResponder:Reload [I] Reloaded Speech responder 1.0.0
2016-10-25T22:35:05 SpeechResponder:Reload [I] Reloaded Speech responder 1.0.0
2016-10-25T22:35:05 SpeechResponder:Reload [I] Reloaded Speech responder 1.0.0
2016-10-25T22:37:13 EDDI:Reload [I] EDDI 2.0.3 stopped
2016-10-25T22:38:20 StarSystemSqLiteRepository:CreateDatabase [I] Updating starsystem repository (1)
2016-10-25T22:48:39 EDDI:Stop [I] EDDI 2.0.3 stopped
2016-10-25T22:48:47 EDDI:.ctor [I] EDDI 2.0.3 starting
2016-10-25T22:48:49 EDDI:.ctor [E] Failed to initialise: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Operator '+' cannot be applied to operand of type 'string'
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at EddiCompanionAppService.CompanionAppService.ModuleFromProfile(String name, Object json)
   at EddiCompanionAppService.CompanionAppService.CompartmentFromProfile(Object json)
   at EddiCompanionAppService.CompanionAppService.ShipFromProfile(Object json)
   at EddiCompanionAppService.CompanionAppService.ProfileFromJson(JObject json)
   at EddiCompanionAppService.CompanionAppService.ProfileFromJson(String data)
   at EddiCompanionAppService.CompanionAppService.Profile()
   at EddiCompanionAppService.CompanionAppService..ctor()
   at EddiCompanionAppService.CompanionAppService.get_Instance()
   at Eddi.EDDI..ctor()
2016-10-25T22:49:00 SpeechResponder:.ctor [I] Initialised Speech responder 1.0.0
2016-10-25T22:49:00 VoiceAttackPlugin:VA_Init1 [I] Initialising EDDI VoiceAttack plugin
2016-10-25T22:49:00 EDDI:.ctor [I] EDDI 2.0.3 starting
2016-10-25T22:49:01 EDDI:.ctor [E] Failed to initialise: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Operator '+' cannot be applied to operand of type 'string'
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at EddiCompanionAppService.CompanionAppService.ModuleFromProfile(String name, Object json)
   at EddiCompanionAppService.CompanionAppService.CompartmentFromProfile(Object json)
   at EddiCompanionAppService.CompanionAppService.ShipFromProfile(Object json)
   at EddiCompanionAppService.CompanionAppService.ProfileFromJson(JObject json)
   at EddiCompanionAppService.CompanionAppService.ProfileFromJson(String data)
   at EddiCompanionAppService.CompanionAppService.Profile()
   at EddiCompanionAppService.CompanionAppService..ctor()
   at EddiCompanionAppService.CompanionAppService.get_Instance()
   at Eddi.EDDI..ctor()
2016-10-25T22:50:12 VoiceAttackPlugin:VA_Exit1 [I] EDDI VoiceAttack plugin exiting
2016-10-25T22:50:12 EDDI:Stop [I] EDDI 2.0.3 stopped
2016-10-25T22:50:37 EDDI:.ctor [I] EDDI 2.0.3 starting
2016-10-25T22:50:38 EDDI:.ctor [E] Failed to initialise: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Operator '+' cannot be applied to operand of type 'string'
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at EddiCompanionAppService.CompanionAppService.ModuleFromProfile(String name, Object json)
   at EddiCompanionAppService.CompanionAppService.CompartmentFromProfile(Object json)
   at EddiCompanionAppService.CompanionAppService.ShipFromProfile(Object json)
   at EddiCompanionAppService.CompanionAppService.ProfileFromJson(JObject json)
   at EddiCompanionAppService.CompanionAppService.ProfileFromJson(String data)
   at EddiCompanionAppService.CompanionAppService.Profile()
   at EddiCompanionAppService.CompanionAppService..ctor()
   at EddiCompanionAppService.CompanionAppService.get_Instance()
   at Eddi.EDDI..ctor()
2016-10-25T22:53:04 SpeechResponder:.ctor [I] Initialised Speech responder 1.0.0
2016-10-25T22:53:04 VoiceAttackPlugin:VA_Init1 [I] Initialising EDDI VoiceAttack plugin
2016-10-25T22:53:04 EDDI:.ctor [I] EDDI 2.0.3 starting
2016-10-25T22:53:05 EDDI:.ctor [E] Failed to initialise: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Operator '+' cannot be applied to operand of type 'string'
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at EddiCompanionAppService.CompanionAppService.ModuleFromProfile(String name, Object json)
   at EddiCompanionAppService.CompanionAppService.CompartmentFromProfile(Object json)
   at EddiCompanionAppService.CompanionAppService.ShipFromProfile(Object json)
   at EddiCompanionAppService.CompanionAppService.ProfileFromJson(JObject json)
   at EddiCompanionAppService.CompanionAppService.ProfileFromJson(String data)
   at EddiCompanionAppService.CompanionAppService.Profile()
   at EddiCompanionAppService.CompanionAppService..ctor()
   at EddiCompanionAppService.CompanionAppService.get_Instance()
   at Eddi.EDDI..ctor()
2016-10-25T23:00:43 VoiceAttackPlugin:VA_Exit1 [I] EDDI VoiceAttack plugin exiting
2016-10-25T23:00:43 EDDI:Stop [I] EDDI 2.0.3 stopped

**Comment by sabreqld** [comment]
![image](https://cloud.githubusercontent.com/assets/16849278/19712371/7be4c4fe-9b80-11e6-8231-3f96cc1d86d7.png)

Same issue, could not restart EDD.EXE until i removed the credentials.json file from
C:\Users\[profile]\AppData\Roaming\EDDI\credentials.json

**Comment by Koifman** [comment]
Same issue as above.

**Comment by willyb321** [comment]
+1

**Comment by bambi72** [comment]
Same here

**Comment by cmdrmcdonald** [comment]
Please could you do the following:

- shut down EDDI
- edit %APPDATA%\EDDI\eddi.json
- set the debug value to be true
- start EDDI
- send me a copy of %APPDATA%\EDDI\eddi.log

so that I can track this down?  Thank you.

**Comment by bambi72** [comment]
Added a clean logfile, it appears to be getting info from the companion app.

[eddi.zip](https://github.com/cmdrmcdonald/EliteDangerousDataProvider/files/552672/eddi.zip)

**Comment by sabreqld** [comment]
[eddi.zip](https://github.com/cmdrmcdonald/EliteDangerousDataProvider/files/552703/eddi.zip)
Uploading my copy as requested

**Comment by Bodybeton** [comment]
[eddi.zip](https://github.com/cmdrmcdonald/EliteDangerousDataProvider/files/552749/eddi.zip)

Here is mine. Thanks for looking into that!

**Comment by cmdrmcdonald** [comment]
Thank you for the uploads.  I believe that the problem has been fixed and a new release (2.0.4) has been issued.  Please download this and let me know if it fixes the issue.

**Comment by bambi72** [comment]
That appears to have done the trick.
Thanks.

**Comment by sabreqld** [comment]
Seems to be working,. no errors have occured and authentication with Frintier was successful.

**Comment by Bodybeton** [comment]
Worked for me also! Thank You Sir! Safe flights!

**Comment by cmdrmcdonald** [comment]
Great to hear.  If there are any further problems like this please open a new issue.
