### ISSUE TITLE
Exploration data sold event error

### ISSUE THREAD

**Issue by omega9380** [cmdrmcdonald/EliteDangerousDataProvider#78]
Whenever I sell exploration data, the ((EDDI exploration data sold)) event is not triggering correctly.  I am running EDDI 2.1.0-b2.

I receive the following error in the log when the event is triggered: 

2016-12-23T18:32:43 VoiceAttackPlugin:VA_Init1 [D] Setting decimal value EDDI exploration data sold reward to 62978 
2016-12-23T18:32:43 VoiceAttackPlugin:VA_Init1 [D] Setting decimal value EDDI exploration data sold bonus to 0 
2016-12-23T18:32:43 SpeechService:speak [D] Selected voice Microsoft Eva Mobile 
2016-12-23T18:32:43 SpeechService:speak [D] Post-selection 
2016-12-23T18:32:43 SpeechService:speak [D] {"standardVoice":"Microsoft Eva Mobile","volume":100,"effectsLevel":0,"distortOnDamage":true,"rate":0,"disablessml":true} 
2016-12-23T18:32:43 SpeechService:speak [D] Feeding normal text to synthesizer: Exploration data for 1 systems sold for Nearly 63 thousand credits. 
2016-12-23T18:32:43 VoiceAttackPlugin:VA_Init1 [W] Failed to handle event System.ArgumentException: Target type System.Collections.IEnumerable is not a value type or a non-abstract class.
Parameter name: targetType
   at Newtonsoft.Json.Utilities.ConvertUtils.Convert(Object initialValue, CultureInfo culture, Type targetType)
   at Newtonsoft.Json.Linq.JValue.JValueDynamicProxy.TryConvert(JValue instance, ConvertBinder binder, Object& result)
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at CallSite.Target(Closure , CallSite , Object )
   at EddiVoiceAttackResponder.VoiceAttackPlugin.setJsonValues(Object& vaProxy, String prefix, Object json, List'1 setKeys)
   at EddiVoiceAttackResponder.VoiceAttackPlugin.setJsonValues(Object& vaProxy, String prefix, Object json, List'1 setKeys)
   at EddiVoiceAttackResponder.VoiceAttackPlugin.<>c__DisplayClass6_0.<VA_Init1>b__0()

**Comment by cmdrmcdonald** [comment]
Thank you for reporting this issue.  It has been fixed and will be available in the next release.
